CREATE DATABASE scandiweb;

CREATE TABLE IF NOT EXISTS `products`(
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `sku` VARCHAR(256) NOT NULL,
    `name` VARCHAR(256),
    `price` FLOAT(11) NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    `value` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id`)
    ) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `products`(
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `sku` VARCHAR(255) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `price` FLOAT UNSIGNED NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    `size` FLOAT UNSIGNED DEFAULT NULL,
    `weight` FLOAT UNSIGNED DEFAULT NULL,
    `height` FLOAT UNSIGNED DEFAULT NULL,
    `width` FLOAT UNSIGNED DEFAULT NULL,
    `length` FLOAT UNSIGNED DEFAULT NULL,
    PRIMARY KEY(`id`)
    ) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT = 1;

/* To Make SKU UNIQUE Field*/
ALTER TABLE products ADD UNIQUE (sku);

